# Generated by Django 5.1.6 on 2025-03-02 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_exercises', to='planner.category'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscle_groups',
            field=models.ManyToManyField(related_name='muscle_exercises', to='planner.musclegroup'),
        ),
    ]
