# Generated by Django 5.1.6 on 2025-03-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_alter_exercise_category_alter_exercise_muscle_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexercise',
            name='exercise_order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
