# Generated by Django 5.1.6 on 2025-03-10 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_alter_workoutexercise_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutday',
            name='description',
        ),
        migrations.RemoveField(
            model_name='workoutday',
            name='name',
        ),
    ]
