# Generated by Django 5.1.6 on 2025-03-13 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_remove_workoutday_description_remove_workoutday_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='currentDay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.workoutday'),
        ),
    ]
