# Generated by Django 5.1.6 on 2025-03-01 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_category_alter_excercise_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
    ]
