# Generated by Django 5.1.6 on 2025-03-02 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_category_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excercise',
            name='category',
        ),
        migrations.RemoveField(
            model_name='excercise',
            name='muscle_groups',
        ),
        migrations.RemoveField(
            model_name='workoutexcercise',
            name='excercise',
        ),
        migrations.RemoveField(
            model_name='workoutday',
            name='workout_plan',
        ),
        migrations.RemoveField(
            model_name='workoutexcercise',
            name='day',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='MuscleGroup',
        ),
        migrations.DeleteModel(
            name='Excercise',
        ),
        migrations.DeleteModel(
            name='WorkoutDay',
        ),
        migrations.DeleteModel(
            name='WorkoutExcercise',
        ),
        migrations.DeleteModel(
            name='WorkoutPlan',
        ),
    ]
